-- 0006: Brief module — daily briefings from analiz event stream
-- One briefing per user per day, generated by LLM from the previous day's events.

create table if not exists public.br_briefings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.sd_profiles(id) on delete cascade,
  brief_date date not null,
  model text,                -- e.g., "claude-haiku-4-5"
  summary text not null,     -- short one-liner
  body_md text not null,     -- full markdown body
  metadata jsonb not null default '{}'::jsonb,  -- stats: event counts, input tokens, etc.
  pushed_at timestamptz,     -- telegram/slack push timestamp
  created_at timestamptz not null default now(),
  unique (user_id, brief_date)
);

create index if not exists br_briefings_user_date_idx
  on public.br_briefings (user_id, brief_date desc);

alter table public.br_briefings enable row level security;

drop policy if exists "br_briefings_self_read" on public.br_briefings;
create policy "br_briefings_self_read" on public.br_briefings
  for select using (auth.uid() = user_id);

-- Admin can read all briefings
drop policy if exists "br_briefings_admin_read" on public.br_briefings;
create policy "br_briefings_admin_read" on public.br_briefings
  for select using (public.sd_is_admin());

-- Writes happen via service_role from the cron/API route (bypasses RLS).
-- No user-level write policy on purpose.
